// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1VtkSzHqn2mElG5-xxOxeXv57AFW2lWc',
    appId: '1:576009720573:web:2c1299f8edf8364cc6a494',
    messagingSenderId: '576009720573',
    projectId: 'news-appd15c21',
    authDomain: 'news-appd15c21.firebaseapp.com',
    storageBucket: 'news-appd15c21.firebasestorage.app',
    measurementId: 'G-NHGDCJFKES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrujHDLnwfjICzWvC6Ms5vLQy3nPpKWjU',
    appId: '1:576009720573:android:77fe7017f520b406c6a494',
    messagingSenderId: '576009720573',
    projectId: 'news-appd15c21',
    storageBucket: 'news-appd15c21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGIw9mJI_GYgkb4Ou0o9csDzgKGx66pwQ',
    appId: '1:576009720573:ios:8b9f8ff1aaf7e76ac6a494',
    messagingSenderId: '576009720573',
    projectId: 'news-appd15c21',
    storageBucket: 'news-appd15c21.firebasestorage.app',
    iosBundleId: 'com.example.newsApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGIw9mJI_GYgkb4Ou0o9csDzgKGx66pwQ',
    appId: '1:576009720573:ios:8b9f8ff1aaf7e76ac6a494',
    messagingSenderId: '576009720573',
    projectId: 'news-appd15c21',
    storageBucket: 'news-appd15c21.firebasestorage.app',
    iosBundleId: 'com.example.newsApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1VtkSzHqn2mElG5-xxOxeXv57AFW2lWc',
    appId: '1:576009720573:web:ae271a381e040205c6a494',
    messagingSenderId: '576009720573',
    projectId: 'news-appd15c21',
    authDomain: 'news-appd15c21.firebaseapp.com',
    storageBucket: 'news-appd15c21.firebasestorage.app',
    measurementId: 'G-8VDE0ZMX1J',
  );
}
